/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liyafeng_jni_Hello */

#ifndef _Included_com_liyafeng_jni_Hello
#define _Included_com_liyafeng_jni_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liyafeng_jni_Hello
 * Method:    doSomething
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liyafeng_jni_Hello_doSomething
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
